# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estepdamda <- function(x, mu, sigma, pro) {
    .Call(`_damda_estepdamda`, x, mu, sigma, pro)
}

ice <- function(Y, z, mu, sigma, ybar, O, obs, ext, nc, C) {
    .Call(`_damda_ice`, Y, z, mu, sigma, ybar, O, obs, ext, nc, C)
}

